// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh6hi_VkS-R8okYc9VttIzUAzxlDWfvGw',
    appId: '1:1038323445648:android:d0e2825110dbefcff80d15',
    messagingSenderId: '1038323445648',
    projectId: 'sayaaratukcom',
    databaseURL: 'https://sayaaratukcom-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sayaaratukcom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj_Fyi4toqbcY1XEsL4JhfI3zeltDQAIk',
    appId: '1:1038323445648:ios:cc413659c1f29f63f80d15',
    messagingSenderId: '1038323445648',
    projectId: 'sayaaratukcom',
    databaseURL: 'https://sayaaratukcom-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sayaaratukcom.appspot.com',
    iosBundleId: 'com.sayaaratukcom.sa',
  );
}
